baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Blacklist'
theme = 'ananke'
metaDataFormat = "yaml"


ignoreLogs = ['warning-goldmark-raw-html']

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 20

[pagination]                                                                                            
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
# background_color_class = "bg-black"
 text_color = "gold"
# custom_css = ["custom.css"]
description = "Crossed off every list."
featured_image_class = "cover bg-top"
recent_posts_number = 3
ignoreLogs = ['warning-goldmark-raw-html']
contentDir = "content"
# body_classes = "avenir bg-near-black"



[params.ananke.social.share]
networks = [


  "email",
  "facebook",
  "bluesky",
  "x-twitter",
  
]

[params.ananke.social.follow]
networks = [
 
  "facebook",
  "bluesky",
  "github",
  "reddit",
  "x-twitter",
  "stackoverflow",
]



[params.ananke.social.facebook]
username = "kellyjamestellez"
# profilelink = "https://www.facebook.com/kellyjamestellez"

[params.ananke.social.x-twitter]
username = "Miblanco4"

[params.ananke.social.bluesky]
username = "don-gato.bsky.social"

[params.ananke.social.github]
username = "Don-Gato-Coded"

[params.ananke.social.reddit]
 username = "DonGatox"

[params.ananke.social.stackoverflow]
username = "1547229/elgatokjt"